name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: finalrepoatest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure Container Registry
      run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_USERNAME }}.azurecr.io --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/$REPO_NAME:latest .
        docker push ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/$REPO_NAME:latest

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: $APP_SERVICE_NAME
        slot-name: production
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
        images: ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/$REPO_NAME:latest