name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-push-to-acr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build Docker image
      run: |
        docker build -t $ACR_NAME.azurecr.io/$REPO_NAME:latest .
        echo "Built Docker image: $ACR_NAME.azurecr.io/$REPO_NAME:latest"

    - name: Push Docker image to ACR
      run: |
        docker push $ACR_NAME.azurecr.io/$REPO_NAME:latest
        echo "Pushed Docker image to ACR"

  deploy-to-app-service:
    needs: build-and-push-to-acr
    runs-on: ubuntu-latest

    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure App Service
      run: |
        az webapp create --name $APP_SERVICE_NAME \
                         --resource-group $RESOURCE_GROUP \
                         --plan $APP_SERVICE_PLAN \
                         --deployment-container-image-name $ACR_NAME.azurecr.io/$REPO_NAME:latest
        echo "Deployment complete: $APP_SERVICE_NAME"