name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REPO_NAME: finalrepoatest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure Container Registry
      run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ secrets.REGISTRY_USERNAME }}.azurecr.io --username ${{ secrets.REGISTRY_USERNAME }} --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/$REPO_NAME:latest .
        docker push ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/$REPO_NAME:latest

    - name: Deploy to Azure Web App
      run: |
          az webapp config container set --name $APP_SERVICE_NAME \
                                         --resource-group $RESOURCE_GROUP_NAME \
                                         --docker-custom-image-name ${{ secrets.REGISTRY_USERNAME }}.azurecr.io/$REPO_NAME:latest \
                                         --docker-registry-server-url https://${{ secrets.REGISTRY_USERNAME }}.azurecr.io \
                                         --docker-registry-server-user ${{ secrets.REGISTRY_USERNAME }} \
                                         --docker-registry-server-password ${{ secrets.REGISTRY_PASSWORD }}